### ISSUE TITLE
Feature: tx-report-queue

### ISSUE THREAD

**Issue by tvanhens** [onyx-platform/onyx-datomic#1]
I think the tx-report-queue would make a great input workflow node. I can attempt to create this but I am both limited in time and knowledge about the plugin extensions. Would this be a possibility? How would I go about creating such a node?

**Comment by MichaelDrogalis** [comment]
I know @robert-stuttaford started to explore this. Not sure how far he got.

I can implement it tonight/this weekend. Or if you'd like to take a crack at it, it'd be similar to reading off a core.async channel. Only one peer at a time can read off the tx-queue.

**Comment by robert-stuttaford** [comment]
Unfortunately I've not had the time - sorry, I have no code to contribute!

**Comment by MichaelDrogalis** [comment]
No prob!

**Comment by tvanhens** [comment]
I'll give it a go. Will sequential consumption ensure that the same peer is reading off the queue? I'm guessing the same same datomic peer needs to be used for the duration of the job since its not guaranteed that datomic peers will be in sync at a given point in time.

**Comment by MichaelDrogalis** [comment]
Exactly right. You can use the Datomic `sync` API to guarantee that, though. The plugin already requires a "t" value for the database.

**Comment by lbradstreet** [comment]
Hi @tvanhens, how'd you go with this? I was about to give the same idea a try.

**Comment by tvanhens** [comment]
Haven't had time for it yet unfortunately. Feel free to give it a go, we may end up just using a dedicated tx-report-queue peer that just puts segments on a hornetq queue rather than using pipeline extensions.

**Comment by hhutch** [comment]
Has anybody done any further work or research into adding a tx-queue watcher?

**Comment by MichaelDrogalis** [comment]
I know @robert-stuttaford has been working on one. Is it in shape to open source or merge into this project, @robert-stuttaford?

**Comment by robert-stuttaford** [comment]
@MichaelDrogalis ~~i'm happy to fork this repo and dump what we have into a file,~~ and take direction from you on how best to bring it into the fold of the rest of the code. that cool? we do have some issues to resolve, still, but it is usable!

i've gisted what we have: https://gist.github.com/robert-stuttaford/3bd5240c988f05092504

**Comment by MichaelDrogalis** [comment]
Thanks @robert-stuttaford. Can you describe the issues you're seeing?

**Comment by lbradstreet** [comment]
I went in a bit of a different directly with this, and used tx-range rather than using the tx-report-queue. This gives us the ability to stop a job and restart from the point that the previous task ended at. It also gives us a way to successfully recover from failures.

The code is up at:
https://github.com/onyx-platform/onyx-datomic/blob/log-api/src/onyx/plugin/datomic.clj#L205
README: https://github.com/onyx-platform/onyx-datomic/blob/log-api/README.md#read-log

I'd love to hear any comments on this direction. @robert-stuttaford, would this method fit your use case?

Cheers

Lucas

**Comment by lbradstreet** [comment]
Btw, the plugin doesn't support checkpointing/fault tolerance yet, but once everyone is happy with it I'll code it in.

**Comment by hhutch** [comment]
@lbradstreet This works for our usecase, thankyou

**Comment by lbradstreet** [comment]
0.7.2.0 released complete with checkpointing
