### ISSUE TITLE
The README lies about `:datomic/written`

### ISSUE THREAD

**Issue by gacelita** [onyx-platform/onyx-datomic#33]
There's no such `:datomic/written` anymore. The commit that removed it is `5d593aad354658a98e478ee15322834b52e71805`. The latest version with `:datomic/written` is `0.9.15.0`.

IMO if the removal is intentional, the README should be updated, else the code should use `:datomic/written` as advertised.

Greets!

**Comment by lbradstreet** [comment]
Thanks for letting me know. We changed the plugin model a lot and it made `:datomic/written` substantially harder to support. I'll remove it.
